[package]
name = "yith"
version = "0.1.0"
authors = ["Don Park <donp@donp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "*"
reqwest = { version = "0.10", features = ["blocking", "json", "socks"] }
secp256k1 = { version = "0.17.2", features = ["recovery"] }
hex = "0.4.0"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
ethabi = "11.0.0"
ethereum-types = "0.8.0"
#ethereum-tx-sign = "3.0.1"
#serde-rlp = "0.1.4"
lettre = { version = "0.9" }
lettre_email = { version = "0.9" }
chrono = "0.4"
num-bigint = "0.2"
bigdecimal = "0.1"
num-traits = "0.2"
clap = {version = "2.33", features = ["yaml"]}
