[package]
name = "yith"
version = "0.1.0"
authors = ["Don Park <donp@donp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "*"
reqwest = { version = "0.10", features = ["blocking", "json"] }
secp256k1 = "0.17.2"
hex = "0.4.0"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
